name: Linux build (default SDCC)

on:
  push:
    branches:
      - master
      - github_actions
    tags:
      - '*'
  pull_request:
    branches:
      - master
      - github_actions

jobs:
  build:
    # need ubuntu 20 for sdcc-3.8 package since ubuntu 18 has old sdcc-3.5
    runs-on: ubuntu-20.04

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Install SDCC
      run: sudo apt-get install -y sdcc

    - name: Build examples
      run: make
      working-directory: examples
